// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgets.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const calculateBudgetSpendAll = `-- name: CalculateBudgetSpendAll :one
SELECT COALESCE(SUM(t.amount), 0)::NUMERIC(12, 2) AS total_spent
FROM
    transactions t
    JOIN bank_accounts ba ON t.plaid_account_id = ba.plaid_account_id
    JOIN plaid_items pi ON ba.plaid_item_id = pi.plaid_item_id
WHERE
    pi.app_user_id = $1
    AND t.transaction_date >= $2
    AND (
        t.transaction_date <= $3
        OR $3 IS NULL
    )
`

type CalculateBudgetSpendAllParams struct {
	AppUserID         uuid.UUID
	TransactionDate   pgtype.Date
	TransactionDate_2 pgtype.Date
}

func (q *Queries) CalculateBudgetSpendAll(ctx context.Context, arg CalculateBudgetSpendAllParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, calculateBudgetSpendAll, arg.AppUserID, arg.TransactionDate, arg.TransactionDate_2)
	var total_spent pgtype.Numeric
	err := row.Scan(&total_spent)
	return total_spent, err
}

const calculateBudgetSpendByCategory = `-- name: CalculateBudgetSpendByCategory :one
SELECT COALESCE(SUM(t.amount), 0)::NUMERIC(12, 2) AS total_spent
FROM
    transactions t
    JOIN bank_accounts ba ON t.plaid_account_id = ba.plaid_account_id
    JOIN plaid_items pi ON ba.plaid_item_id = pi.plaid_item_id
WHERE
    pi.app_user_id = $1
    AND UPPER(t.personal_finance_category) = UPPER($2)
    AND t.transaction_date >= $3
    AND (
        t.transaction_date <= $4
        OR $4 IS NULL
    )
`

type CalculateBudgetSpendByCategoryParams struct {
	AppUserID         uuid.UUID
	Upper             interface{}
	TransactionDate   pgtype.Date
	TransactionDate_2 pgtype.Date
}

func (q *Queries) CalculateBudgetSpendByCategory(ctx context.Context, arg CalculateBudgetSpendByCategoryParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, calculateBudgetSpendByCategory,
		arg.AppUserID,
		arg.Upper,
		arg.TransactionDate,
		arg.TransactionDate_2,
	)
	var total_spent pgtype.Numeric
	err := row.Scan(&total_spent)
	return total_spent, err
}

const createBudget = `-- name: CreateBudget :one
INSERT INTO
    budgets (
        app_user_id,
        name,
        category,
        limit_amount,
        budget_period,
        start_date,
        end_date
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id, app_user_id, name, category, limit_amount, amount_spent, budget_period, start_date, end_date, created_at
`

type CreateBudgetParams struct {
	AppUserID    uuid.UUID
	Name         string
	Category     pgtype.Text
	LimitAmount  pgtype.Numeric
	BudgetPeriod string
	StartDate    pgtype.Date
	EndDate      pgtype.Date
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.AppUserID,
		arg.Name,
		arg.Category,
		arg.LimitAmount,
		arg.BudgetPeriod,
		arg.StartDate,
		arg.EndDate,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.AppUserID,
		&i.Name,
		&i.Category,
		&i.LimitAmount,
		&i.AmountSpent,
		&i.BudgetPeriod,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets WHERE id = $1
`

func (q *Queries) DeleteBudget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBudget, id)
	return err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT id, app_user_id, name, category, limit_amount, amount_spent, budget_period, start_date, end_date, created_at FROM budgets WHERE id = $1
`

func (q *Queries) GetBudgetByID(ctx context.Context, id uuid.UUID) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByID, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.AppUserID,
		&i.Name,
		&i.Category,
		&i.LimitAmount,
		&i.AmountSpent,
		&i.BudgetPeriod,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const getBudgetsByUserID = `-- name: GetBudgetsByUserID :many
SELECT id, app_user_id, name, category, limit_amount, amount_spent, budget_period, start_date, end_date, created_at FROM budgets WHERE app_user_id = $1 ORDER BY name
`

func (q *Queries) GetBudgetsByUserID(ctx context.Context, appUserID uuid.UUID) ([]Budget, error) {
	rows, err := q.db.Query(ctx, getBudgetsByUserID, appUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.AppUserID,
			&i.Name,
			&i.Category,
			&i.LimitAmount,
			&i.AmountSpent,
			&i.BudgetPeriod,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets
SET
    name = COALESCE(NULLIF($2, ''), name),
    category = CASE
        WHEN $3::BOOLEAN THEN $4
        ELSE category
    END,
    limit_amount = CASE
        WHEN $5::NUMERIC(12, 2) IS NOT NULL THEN $5
        ELSE limit_amount
    END,
    budget_period = COALESCE(NULLIF($6, ''), budget_period),
    start_date = CASE
        WHEN $7::DATE IS NOT NULL THEN $7
        ELSE start_date
    END,
    end_date = CASE
        WHEN $8::BOOLEAN THEN $9
        ELSE end_date
    END
WHERE
    id = $1
RETURNING
    id, app_user_id, name, category, limit_amount, amount_spent, budget_period, start_date, end_date, created_at
`

type UpdateBudgetParams struct {
	ID       uuid.UUID
	Column2  interface{}
	Column3  bool
	Category pgtype.Text
	Column5  pgtype.Numeric
	Column6  interface{}
	Column7  pgtype.Date
	Column8  bool
	EndDate  pgtype.Date
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudget,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Category,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.EndDate,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.AppUserID,
		&i.Name,
		&i.Category,
		&i.LimitAmount,
		&i.AmountSpent,
		&i.BudgetPeriod,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const updateBudgetAmountSpent = `-- name: UpdateBudgetAmountSpent :one
UPDATE budgets SET amount_spent = $2 WHERE id = $1 RETURNING id, app_user_id, name, category, limit_amount, amount_spent, budget_period, start_date, end_date, created_at
`

type UpdateBudgetAmountSpentParams struct {
	ID          uuid.UUID
	AmountSpent pgtype.Numeric
}

func (q *Queries) UpdateBudgetAmountSpent(ctx context.Context, arg UpdateBudgetAmountSpentParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudgetAmountSpent, arg.ID, arg.AmountSpent)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.AppUserID,
		&i.Name,
		&i.Category,
		&i.LimitAmount,
		&i.AmountSpent,
		&i.BudgetPeriod,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}
