// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgets.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO
    budgets (
        user_id,
        category,
        limit_amount,
        period,
        start_date,
        end_date
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, user_id, category, limit_amount, period, start_date, end_date, created_at
`

type CreateBudgetParams struct {
	UserID      uuid.UUID
	Category    string
	LimitAmount string
	Period      string
	StartDate   time.Time
	EndDate     sql.NullTime
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, createBudget,
		arg.UserID,
		arg.Category,
		arg.LimitAmount,
		arg.Period,
		arg.StartDate,
		arg.EndDate,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.LimitAmount,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets WHERE id = $1
`

func (q *Queries) DeleteBudget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBudget, id)
	return err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT id, user_id, category, limit_amount, period, start_date, end_date, created_at FROM budgets WHERE id = $1
`

func (q *Queries) GetBudgetByID(ctx context.Context, id uuid.UUID) (Budget, error) {
	row := q.db.QueryRowContext(ctx, getBudgetByID, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.LimitAmount,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const getBudgetsByUserID = `-- name: GetBudgetsByUserID :many
SELECT id, user_id, category, limit_amount, period, start_date, end_date, created_at FROM budgets WHERE user_id = $1 ORDER BY category
`

func (q *Queries) GetBudgetsByUserID(ctx context.Context, userID uuid.UUID) ([]Budget, error) {
	rows, err := q.db.QueryContext(ctx, getBudgetsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.LimitAmount,
			&i.Period,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
