// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: linked_accounts.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const createLinkedAccount = `-- name: CreateLinkedAccount :one
INSERT INTO
    linked_accounts (
        user_id,
        plaid_item_id,
        plaid_access_token,
        institution_name,
        account_name,
        account_type,
        current_balance,
        available_balance
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
    )
RETURNING
    id, user_id, plaid_item_id, plaid_access_token, institution_name, account_name, account_type, current_balance, available_balance, last_synced_at
`

type CreateLinkedAccountParams struct {
	UserID           uuid.UUID
	PlaidItemID      string
	PlaidAccessToken string
	InstitutionName  string
	AccountName      string
	AccountType      string
	CurrentBalance   string
	AvailableBalance string
}

func (q *Queries) CreateLinkedAccount(ctx context.Context, arg CreateLinkedAccountParams) (LinkedAccount, error) {
	row := q.db.QueryRowContext(ctx, createLinkedAccount,
		arg.UserID,
		arg.PlaidItemID,
		arg.PlaidAccessToken,
		arg.InstitutionName,
		arg.AccountName,
		arg.AccountType,
		arg.CurrentBalance,
		arg.AvailableBalance,
	)
	var i LinkedAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlaidItemID,
		&i.PlaidAccessToken,
		&i.InstitutionName,
		&i.AccountName,
		&i.AccountType,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.LastSyncedAt,
	)
	return i, err
}

const getLinkedAccountByID = `-- name: GetLinkedAccountByID :one
SELECT id, user_id, plaid_item_id, plaid_access_token, institution_name, account_name, account_type, current_balance, available_balance, last_synced_at FROM linked_accounts WHERE id = $1
`

func (q *Queries) GetLinkedAccountByID(ctx context.Context, id uuid.UUID) (LinkedAccount, error) {
	row := q.db.QueryRowContext(ctx, getLinkedAccountByID, id)
	var i LinkedAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlaidItemID,
		&i.PlaidAccessToken,
		&i.InstitutionName,
		&i.AccountName,
		&i.AccountType,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.LastSyncedAt,
	)
	return i, err
}

const getLinkedAccountByPlaidItemID = `-- name: GetLinkedAccountByPlaidItemID :one
SELECT id, user_id, plaid_item_id, plaid_access_token, institution_name, account_name, account_type, current_balance, available_balance, last_synced_at FROM linked_accounts WHERE plaid_item_id = $1 LIMIT 1
`

func (q *Queries) GetLinkedAccountByPlaidItemID(ctx context.Context, plaidItemID string) (LinkedAccount, error) {
	row := q.db.QueryRowContext(ctx, getLinkedAccountByPlaidItemID, plaidItemID)
	var i LinkedAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlaidItemID,
		&i.PlaidAccessToken,
		&i.InstitutionName,
		&i.AccountName,
		&i.AccountType,
		&i.CurrentBalance,
		&i.AvailableBalance,
		&i.LastSyncedAt,
	)
	return i, err
}

const getLinkedAccountsByUserID = `-- name: GetLinkedAccountsByUserID :many
SELECT id, user_id, plaid_item_id, plaid_access_token, institution_name, account_name, account_type, current_balance, available_balance, last_synced_at
FROM linked_accounts
WHERE
    user_id = $1
ORDER BY institution_name, account_name
`

func (q *Queries) GetLinkedAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]LinkedAccount, error) {
	rows, err := q.db.QueryContext(ctx, getLinkedAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkedAccount
	for rows.Next() {
		var i LinkedAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlaidItemID,
			&i.PlaidAccessToken,
			&i.InstitutionName,
			&i.AccountName,
			&i.AccountType,
			&i.CurrentBalance,
			&i.AvailableBalance,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE linked_accounts
SET
    current_balance = $2,
    available_balance = $3,
    last_synced_at = now()
WHERE
    id = $1
`

type UpdateAccountBalanceParams struct {
	ID               uuid.UUID
	CurrentBalance   string
	AvailableBalance string
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountBalance, arg.ID, arg.CurrentBalance, arg.AvailableBalance)
	return err
}
