// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type BankAccount struct {
	ID               uuid.UUID
	ItemID           uuid.UUID
	PlaidAccountID   string
	AccountName      string
	OfficialName     sql.NullString
	AccountType      string
	AccountSubtype   sql.NullString
	CurrentBalance   string
	AvailableBalance string
	IsoCurrencyCode  string
	UpdatedAt        time.Time
}

type Budget struct {
	ID           uuid.UUID
	AppUserID    uuid.UUID
	Category     string
	LimitAmount  string
	BudgetPeriod string
	StartDate    time.Time
	EndDate      sql.NullTime
	CreatedAt    time.Time
}

type PlaidItem struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	PlaidItemID      string
	PlaidAccessToken string
	InstitutionName  string
	PlaidCursor      sql.NullString
	LastSyncedAt     sql.NullTime
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Transaction struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	TransactionDate time.Time
	TransactionName string
	Category        string
	Amount          string
	Pending         bool
	CreatedAt       time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
