// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Budget struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Category    string
	LimitAmount string
	Period      string
	StartDate   time.Time
	EndDate     sql.NullTime
	CreatedAt   time.Time
}

type LinkedAccount struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	PlaidItemID      string
	PlaidAccessToken string
	InstitutionName  string
	AccountName      string
	AccountType      string
	CurrentBalance   string
	AvailableBalance string
	LastSyncedAt     sql.NullTime
}

type Transaction struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	Date      time.Time
	Name      string
	Category  string
	Amount    string
	Pending   bool
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
