// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plaid_items.sql

package sqlcdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPlaidItem = `-- name: CreatePlaidItem :one
INSERT INTO
    plaid_items (
        user_id,
        plaid_item_id,
        plaid_access_token,
        institution_name
    )
VALUES ($1, $2, $3, $4)
RETURNING
    id, user_id, plaid_item_id, plaid_access_token, institution_name, plaid_cursor, last_synced_at, created_at, updated_at
`

type CreatePlaidItemParams struct {
	UserID           uuid.UUID
	PlaidItemID      string
	PlaidAccessToken string
	InstitutionName  string
}

func (q *Queries) CreatePlaidItem(ctx context.Context, arg CreatePlaidItemParams) (PlaidItem, error) {
	row := q.db.QueryRowContext(ctx, createPlaidItem,
		arg.UserID,
		arg.PlaidItemID,
		arg.PlaidAccessToken,
		arg.InstitutionName,
	)
	var i PlaidItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlaidItemID,
		&i.PlaidAccessToken,
		&i.InstitutionName,
		&i.PlaidCursor,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaidItemByID = `-- name: GetPlaidItemByID :one
SELECT id, user_id, plaid_item_id, plaid_access_token, institution_name, plaid_cursor, last_synced_at, created_at, updated_at FROM plaid_items WHERE id = $1
`

func (q *Queries) GetPlaidItemByID(ctx context.Context, id uuid.UUID) (PlaidItem, error) {
	row := q.db.QueryRowContext(ctx, getPlaidItemByID, id)
	var i PlaidItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlaidItemID,
		&i.PlaidAccessToken,
		&i.InstitutionName,
		&i.PlaidCursor,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaidItemByPlaidItemID = `-- name: GetPlaidItemByPlaidItemID :one
SELECT id, user_id, plaid_item_id, plaid_access_token, institution_name, plaid_cursor, last_synced_at, created_at, updated_at FROM plaid_items WHERE plaid_item_id = $1 LIMIT 1
`

func (q *Queries) GetPlaidItemByPlaidItemID(ctx context.Context, plaidItemID string) (PlaidItem, error) {
	row := q.db.QueryRowContext(ctx, getPlaidItemByPlaidItemID, plaidItemID)
	var i PlaidItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlaidItemID,
		&i.PlaidAccessToken,
		&i.InstitutionName,
		&i.PlaidCursor,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaidItemsByUserID = `-- name: GetPlaidItemsByUserID :many
SELECT id, user_id, plaid_item_id, plaid_access_token, institution_name, plaid_cursor, last_synced_at, created_at, updated_at
FROM plaid_items
WHERE
    user_id = $1
ORDER BY institution_name
`

func (q *Queries) GetPlaidItemsByUserID(ctx context.Context, userID uuid.UUID) ([]PlaidItem, error) {
	rows, err := q.db.QueryContext(ctx, getPlaidItemsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaidItem
	for rows.Next() {
		var i PlaidItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlaidItemID,
			&i.PlaidAccessToken,
			&i.InstitutionName,
			&i.PlaidCursor,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlaidItemCursor = `-- name: UpdatePlaidItemCursor :exec
UPDATE plaid_items
SET
    plaid_cursor = $2,
    last_synced_at = now(),
    updated_at = now()
WHERE
    id = $1
`

type UpdatePlaidItemCursorParams struct {
	ID          uuid.UUID
	PlaidCursor sql.NullString
}

func (q *Queries) UpdatePlaidItemCursor(ctx context.Context, arg UpdatePlaidItemCursorParams) error {
	_, err := q.db.ExecContext(ctx, updatePlaidItemCursor, arg.ID, arg.PlaidCursor)
	return err
}
