// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO
    transactions (
        account_id,
        date,
        name,
        category,
        amount,
        pending
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, account_id, date, name, category, amount, pending, created_at
`

type CreateTransactionParams struct {
	AccountID uuid.UUID
	Date      time.Time
	Name      string
	Category  string
	Amount    string
	Pending   bool
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.AccountID,
		arg.Date,
		arg.Name,
		arg.Category,
		arg.Amount,
		arg.Pending,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Date,
		&i.Name,
		&i.Category,
		&i.Amount,
		&i.Pending,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionsByAccountID = `-- name: GetTransactionsByAccountID :many
SELECT id, account_id, date, name, category, amount, pending, created_at FROM transactions WHERE account_id = $1 ORDER BY date DESC
`

func (q *Queries) GetTransactionsByAccountID(ctx context.Context, accountID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Name,
			&i.Category,
			&i.Amount,
			&i.Pending,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByUserID = `-- name: GetTransactionsByUserID :many
SELECT t.id, t.account_id, t.date, t.name, t.category, t.amount, t.pending, t.created_at
FROM
    transactions t
    JOIN linked_accounts la ON t.account_id = la.id
WHERE
    la.user_id = $1
ORDER BY t.date DESC
`

func (q *Queries) GetTransactionsByUserID(ctx context.Context, userID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Name,
			&i.Category,
			&i.Amount,
			&i.Pending,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTransaction = `-- name: UpsertTransaction :one
INSERT INTO
    transactions (
        account_id,
        date,
        name,
        category,
        amount,
        pending
    )
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO
UPDATE
SET
    date = EXCLUDED.date,
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    amount = EXCLUDED.amount,
    pending = EXCLUDED.pending
RETURNING
    id, account_id, date, name, category, amount, pending, created_at
`

type UpsertTransactionParams struct {
	AccountID uuid.UUID
	Date      time.Time
	Name      string
	Category  string
	Amount    string
	Pending   bool
}

func (q *Queries) UpsertTransaction(ctx context.Context, arg UpsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, upsertTransaction,
		arg.AccountID,
		arg.Date,
		arg.Name,
		arg.Category,
		arg.Amount,
		arg.Pending,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Date,
		&i.Name,
		&i.Category,
		&i.Amount,
		&i.Pending,
		&i.CreatedAt,
	)
	return i, err
}
